apiVersion: v1
kind: Service
metadata:
  name: jsc-opencode-web
  namespace: opencode-ns
spec:
  type: ClusterIP
  selector:
    app: jsc-opencode-web
  ports:
    - name: http
      port: 4096
      targetPort: 4096
      protocol: TCP
