apiVersion: v1
kind: Service
metadata:
  name: jsc-gateway-svc
  namespace: opencode-ns
  labels:
    app: jsc-gateway-app
spec:
  type: LoadBalancer
  ports:
    - port: 3030
      targetPort: 3000
  selector:
    app: jsc-gateway-app
    tier: frontend
